### ISSUE TITLE
TPKeyboardAvoidingTableView stopped working on 1.2.5+

### ISSUE THREAD

**Issue by aviramuse** [michaeltyson/TPKeyboardAvoiding#161] opened 2015-03-16 14:52 UTC
I've been using ```TPKeyboardAvoidingTableView``` for a long time, and ever since I upgraded the Podfile to version 1.2.5 or to 1.2.6 it stopped working -  the keyboard is hiding the lower part of my table.

When I downgraded the pod to version 1.2.4 it worked again, so for now I'm sticking with 1.2.4.

**Comment by pzgz** [comment] 2015-03-16 18:35
Right, same here, roll back to 1.2.4 and it's working now.

**Comment by claudiumatei** [comment] 2015-03-20 20:58
rolling back to 1.2.4 didn't fix the problem for me :(

**Comment by bahsan** [comment] 2015-05-04 10:12
Same here, 1.2.5+ not working correctly on iOS 7. Downgrading to 1.2.4 required to make it work.

**Comment by cliftonlabrum** [comment] 2015-05-07 18:18
Same issue here. Had to install this specific version in my Podfile: `pod 'TPKeyboardAvoiding', '1.2.4'`

**Comment by ren6** [comment] 2015-05-18 14:12
Same issue

**Comment by cliftonlabrum** [comment] 2015-05-18 16:40
It seems that on iOS 8.3, this issue happens even with version `1.2.4`. If I focus a `UITextField` then hide the keyboard, the `UITableViewController`'s scroll view is messed up and I can't see the lower portion of the table.

**Comment by ren6** [comment] 2015-05-18 19:18
@cliftonlabrum I fixed it by switching my controller from UITableviewController to UIViewcontroller

**Comment by erichedstrom** [comment] 2015-05-24 21:43
I have run into this as well. I narrowed it down to this change merged on November 3 in commit eeb4cf0.

    if (!firstResponder) {
        return;
    }
    
The funny thing is I have two table views in my screen. One or the other is visible depending on which text field above the table views is first responder. With this change, the second table works better with the iOS 8 autosuggest, but the first table is much worse, with much of the table buried under the keyboard.

**Comment by michaeltyson** [comment] 2015-06-29 06:16
This should be sorted in the latest version. Problem appears to be caused by some undocumented new behaviour

**Comment by aviramuse** [comment] 2015-07-07 09:10
Version 1.2.8 is still buggy and not working for us on iOS 8.3 and above.

**Comment by michaeltyson** [comment] 2015-07-07 09:11
Could you describe your setup - ideally, create a sample app that demonstrates the problem (or modify the existing one)?

**Comment by shanegao** [comment] 2015-07-08 07:46
@michaeltyson For my case, assign UITableView of UITableViewController to TPKeyboardAvoidingTableView, step debug in this method: `hasAutomaticKeyboardAvoidingBehaviour `
self.delegate is `nil` in the awakeFromNib. so the keyboard status observes did not register successfully

**Comment by michaeltyson** [comment] 2015-07-08 07:54
Oh, that's weird. Why is delegate nil, at that point? Usually the UITableViewController is always the delegate...

**Comment by michaeltyson** [comment] 2015-07-08 07:55
By the way: you don't need TPKeyboardAvoiding at all now if you're using UITableViewController. That code just checks to see if you're using UITableViewController, and disables TPKeyboardAvoiding if you are.

**Comment by shanegao** [comment] 2015-07-08 08:05
Thanks for your response, you mean, I should do nothing if using UITableViewController, the keyboard will not avoid user input, right? but it did not work well indeed.

**Comment by michaeltyson** [comment] 2015-07-08 08:07
Would you create a sample app that demonstrates the issue? Might be simplest.

**Comment by sschale** [comment] 2015-07-09 04:41
Using 8.4, standard UITableView didn't have auto-scrolling functionality, disabling your 8.3 check returned  the expected functionality when using TPKeyboardAvoidingTableView for me. With the check on, no avoiding or height adjustments were done. Stock keyboard on simulator and iPhone 6, with tableviewcontroller inside a nav and tab controller.

**Comment by michaeltyson** [comment] 2015-07-09 04:42
Can you confirm the issue occurs for you with the included sample app?

**Comment by sschale** [comment] 2015-07-09 04:46
It does not occur in the sample app, the code works as is fine in the simulator, even when I enclosed in a nav bar.

**Comment by michaeltyson** [comment] 2015-07-09 04:47
Okay. I think it'd still be best if you could create a sample app demonstrating your issue, if you're truly using a UITableViewController, because I can't reproduce this =)

**Closed** 2015-07-23 07:31 UTC

**Comment by KileyCaravella** [comment] 2017-09-14 17:34
I'm actually having this issue again in 1.3.1 using TableViewControllers! I'm taking the advice of others in this thread and changing it to a ViewController and connecting the tableView to it, but I wanted to post this here in case others were also experiencing this
