### ISSUE TITLE
TPKeyboardAvoidingScrollView not working at all at version 1.2.2 via cocoapods

### ISSUE THREAD

**Issue by chadkouse** [michaeltyson/TPKeyboardAvoiding#87] opened 2014-02-04 22:00 UTC
reverting to 1.2.1 solves the problem.  I really don't know enough about the project to provide more details other than I tested this with a simple UIView containing a UIScrollView (set to TPKeyboardAvoidingScrollView) and a single UITextField at the bottom of the screen.

Did not set the delegate, so it's running off of the notifications.

Update: setting the delegate didn't help either.

**Comment by foffux** [comment] 2015-02-10 15:32
I am experimenting same issue, TPKeyboardAvoidingScrollView is not working at all after moving to iOS 8. I cannot even see the keyboard to appear. Revert back not working at all.

**Comment by michaeltyson** [comment] 2015-02-10 23:39
I'm unable to reproduce this on the sample app; can you put together something that demonstrates the issue?

**Comment by foffux** [comment] 2015-02-11 15:24
Hello.
There are a couple of issue I guess with high priority.

First one, related to this issue, I guess not already solved yet but important:

https://github.com/michaeltyson/TPKeyboardAvoiding/issues/75

when you perform an installation with cocoa pods simply run the controller, you get:

[TPKeyboardAvoidingScrollView TPKeyboardAvoiding_updateContentInset]: unrecognized selector sent to instance

Simply add UIScrollView+TPKeyboardAvoidingAdditions.m to my main project as resource to be compiled it disappears, even if it was already added to pods related project. I think it was not good at all and this happens just with new iOS 8 SDK (Xcode 6). Maybe a issue related to cocoa pods? I am using latest version, 0.35.0.

Second one, more important: using iOS 8 SDK as a base but running the controller under iOS 7 Simulator you cannot see even the keyboard to appear. Everything goes right if iOS 8 simulator is used.
To see this issue, to answer you question, I just run your sample project, once compiled with iOS 8 SDK, into iOS 7 Simulator. If you pick "View", "Table" or "CollectionView" is the same, keyboard won't even appear. Just try.

**Comment by foffux** [comment] 2015-02-11 15:41
Related to the second issue I told you before, I opened another issue you can take care of:

TPKeyboardAvoiding not working at all when using IOS 8.1 SDK and IOS 7.1 Simulator #154

Thank you.

**Comment by mklimek** [comment] 2015-02-12 08:18
It works fine for iOS 8.1 iPhone 4s Simulator, but the same project for iOS 8.1 iPhone 6 Simulator it dosen't. Keyboard doesn't pop up.

**Comment by foffux** [comment] 2015-02-12 08:28
I am not experimenting the same issue, because with iOS 8 and iOS 8 Simulator everything is fine, but with iOS 7 Simulator keyboard does not pop up. I do not know if this is an issue related to Apple Simulator or it is an issue of this controller. Michael can you tell us something about it, please. I will try on real device but I would happy to know something from you since you can actually understand if it is an issue.
Thank you very much.

**Comment by foffux** [comment] 2015-02-12 10:45
Hello every one. I think I have found the actual problem. I am speaking about iOS 7 Simulator issue (keyboard does not pop up). Read this, they hall me solve this issue. Days wasted anyway...Hope this helps.

http://stackoverflow.com/questions/25842168/cant-find-keyplane-that-supports-type-4-for-keyboard-iphone-portrait-numberpad/25954053#25954053
http://stackoverflow.com/questions/24871532/xcode-ios-8-keyboard-types-not-supported

**Comment by mklimek** [comment] 2015-02-12 11:01
@foffux thank you, it helped.

**Comment by foffux** [comment] 2015-02-12 11:08
Glad to hear that. Xcode 6 sucks....

**Comment by michaeltyson** [comment] 2015-02-12 23:24
Glad you guys figured it out =) Good to know.

**Closed** 2015-02-12 23:24 UTC
